### ISSUE TITLE
installation fails...

### ISSUE THREAD

**Issue by tofixx** [heimrichhannot/contao-member_plus#5]
Is this an generic error or do I have an error in my installation?
Contao Version is 4.4.8

```
Using version ^2.1 for heimrichhannot/contao-member_plus
/var/www/.../composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 4 installs, 0 updates, 0 removals
  - Installing codefog/contao-haste (4.17.7): Loading from cache

Installation failed, reverting /var/www/.../composer.json to its original content.
--------------------------------------------------------
Exception occured: Installation target "/var/www/.../system/modules/haste" already exists
#0 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#3 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/client...')
#4 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(876): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/.../web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/.../web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/.../web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: Installation target "/var/www/.../system/modules/haste" already exists
#0 /var/www/.../vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(512): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->canAddTarget('/var/www/client...', 3)
#1 /var/www/.../vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(251): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->canAddSymlink('/var/www/client...', '/var/www/client...', 3)
#2 /var/www/.../vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(116): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->addSymlinks(Object(Composer\Package\CompletePackage), '/var/www/client...', Array)
#3 phar:///var/www/.../web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(173): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar:///var/www/.../web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#5 phar:///var/www/.../web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(587): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#6 phar:///var/www/.../web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(223): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar:///var/www/.../web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/RequireCommand.php(180): Composer\Installer->run()
#8 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#10 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#11 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#12 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#13 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/client...')
#14 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///var/www/.../web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(876): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///var/www/.../web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///var/www/.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///var/www/.../web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/.../web/contao-manager.phar.php(55): require('phar:///var/www...')
#22 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by fatcrobat** [comment]
The error says `system/modules/haste` already exists. Just delete `system/modules/haste` and `vendor/codefog/contao-haste` directory and run composer again. `haste` is a subdependency and will be reinstalled. Looks for me like an error related to the `contao-community-alliance/composer-plugin` that does not overwrite symlinks of contao 3 modules right.
